### ISSUE TITLE
Upadte the UI of main page

### ISSUE THREAD

**Issue by bhavesh0206s** [bhavesh0206s/emaily#5]

**Comment by dfoltynski** [comment]
can you assign me? I will provide screenshots of prototype design first

**Comment by bhavesh0206s** [comment]
Go ahead @dfoltynski

**Comment by dfoltynski** [comment]
@bhavesh0206s 
Error: Cannot find module './dev'

**Comment by bhavesh0206s** [comment]
I have made the changes try now

**Comment by dfoltynski** [comment]
@bhavesh0206s 
There is no content, you basically want to change how does it looks like?
![image](https://user-images.githubusercontent.com/53613664/95589177-aeb3b980-0a44-11eb-8731-ce1801489608.png)

**Comment by bhavesh0206s** [comment]
You can add background and change the text style.

**Comment by dfoltynski** [comment]
@bhavesh0206s 
![image](https://user-images.githubusercontent.com/53613664/95599871-f1c85980-0a51-11eb-894f-41823438ce0a.png)
![image](https://user-images.githubusercontent.com/53613664/95599897-fa209480-0a51-11eb-8c67-2c7a835ec7fc.png)
![image](https://user-images.githubusercontent.com/53613664/95599923-01e03900-0a52-11eb-8b02-988a3aceeb9a.png)
Which one u want?

**Comment by bhavesh0206s** [comment]
2nd one

**Comment by bhavesh0206s** [comment]
use inline styling or create one

**Comment by dfoltynski** [comment]
@bhavesh0206s done. You can review it 😊
