### ISSUE TITLE
Display google icon 

### ISSUE THREAD

**Issue by bhavesh0206s** [bhavesh0206s/emaily#6]
Display google login icon instead of login with google

**Comment by bhavesh0206s** [comment]
Like below 
https://www.google.com/search?q=login+with+google&client=firefox-b-d&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiNzqP47qbsAhV6IbcAHWFHDmAQ_AUoAXoECBYQAw&biw=1536&bih=750#imgrc=8Fn2xxwiQ1VY6M

**Comment by julieg18** [comment]
I can help! If I'm understanding this correctly, you want to place the google icon next to the text, "Login with Google"

**Comment by bhavesh0206s** [comment]
Blue one.
I have assigned you the issue.

**Comment by julieg18** [comment]
If I need to add extra CSS to the button, should I place the CSS in a separate file, or use inline styling?

**Comment by bhavesh0206s** [comment]
Use inline styling
